演習2-12の追加
ddt-sugiura/meikai_cpp_sugiura pull request #1
Opened 2021-11-18 10:31 UTC by ddt-sugiura

演習2-12のソースコードを上げました。確認のほどよろしくお願いします。

2022-01-26 12:19 UTC, ddt-mentor requested changes

2022-01-26 12:19 UTC, ddt-mentor commented on cpp-2-12/src/cpp-2-12.cpp
> +	cout << "整数a："; cin >> a;
";"の後は必ず改行するようにしてください。(石井)

2022-01-26 12:19 UTC, ddt-mentor commented on cpp-2-12/src/cpp-2-12.cpp
> +	int a,b;
原則として、全てのステップにコメントを入れてください。(石井)

2022-02-16 12:00 UTC, ddt-sugiura commented
演習2-12コミット

2022-02-16 12:01 UTC, merged