Add files via upload
ddt-sugiura/meikai_cpp_sugiura pull request #21
Opened 2022-09-28 11:40 UTC by ddt-sugiura

演習5-8を実装しました。確認のほどよろしくお願いします。

2022-09-28 12:28 UTC, ddt-mentor requested changes

2022-09-28 12:28 UTC, ddt-mentor commented on 演習5-8.cpp
> +	const int DUMMY_INTEGER = 20;
柴田
入っていない値を定義する場合、元の値より大きい数よりは、負の値を個人的にはお勧めします。
又は INT_MAX 等まずありえない値としておいてください。
※現時点では1～10ですが、仕様変更等で10～20になった場合等にバグの元となります。

2022-09-28 12:28 UTC, ddt-mentor commented on 演習5-8.cpp
> +		int randElement = rand() % 10;
柴田
この 10で割った余りの使用方法は危険です。配列数が変更となった場合に対応できません。
この結果（randElement）を何に使うか再確認したうえで、10ではなく定数を使用してください。

2022-10-05 12:18 UTC, ddt-sugiura commented
演習5-8を修正しましたので確認のほどよろしくお願いします

2022-10-12 09:50 UTC, merged